communitiesuk/digital-form-builder

model/src/data-model/types.ts, model/src/schema/schema.ts, runner/src/client/sass/application.scss, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/views/partials/form.html, runner/src/server/plugins/engine/views/partials/heading.html, runner/src/server/views/404.html, runner/src/server/views/500.html, runner/src/server/views/help/accessibility-statement.html, runner/src/server/views/help/cookies.html, runner/src/server/views/help/privacy.html, runner/src/server/views/help/terms-and-conditions.html, runner/src/server/views/layout.html, runner/src/server/views/repeating-summary.html, runner/src/server/views/summary.html, runner/src/server/views/timeout.html, runner/test/cases/server/plugins/router.test.ts
- Pulling in changes from main
[] pipeline succeeded, affected functionality still working
=> Updating Main from Xforms

runner/config/custom-environment-variables.json, runner/config/default.js, runner/package.json, runner/src/server/plugins/engine/plugin.ts, runner/src/server/services/uploadService.ts, runner/src/server/utils/configSchema.ts, yarn.lock
- Uploading of files to an s3 bucket
GET: paas-s3-broker-prod-lon-443b9fc2-55ff-4c2f-9ac3-d3ebfb18ef5a.s3.eu-west-2.amazonaws.com/{filename}
=> FS-1209 Store uploaded files securely

runner/src/server/plugins/engine/views/partials/form.html, runner/src/server/views/summary.html, smoke-tests/designer/features/pageComponents.feature, smoke-tests/designer/features/steps/steps.js
- `Continue `button renamed to `Save and continue`
- New feature (non-breaking change which adds functionality)
- smoke tests
=> FS 1194 save and continue button

runner/src/server/plugins/engine/components/MultiInputField.ts
if add another component value is None, continue with None value else iterate though values. 
- Tested locally
=> 🐛  minor bug fix:

runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/src/server/plugins/initialiseSession/types.ts, runner/src/server/schemas/types.ts, runner/src/server/schemas/webhookSchema.ts
- [FS-1220](https://digital.dclg.gov.uk/jira/browse/FS-1220) is the related change. Added an option to be passed into the runner. Second part to this is on the front end which will pass the redirect value in
Launch runner and front end
Navigate to task list
complete a section
after summary should redirect to task list
Before PR's can be merged they will need to be tested by QA and …
=> FS-1220-Summary now redirects to link provided

runner/src/server/plugins/engine/models/SummaryViewModel.ts
- Fix for title on the summary page
=> Title on Summary page fix

runner/src/server/plugins/engine/components/FileUploadField.ts, runner/src/server/services/uploadService.ts, runner/test/cases/server/upload.test.js
=> Adding more file name formats

runner/src/server/views/layout.html
- Cookie banner has been removed from the top of the page
=> Removal of the cookie banner

designer/client/conditions/InlineConditions.tsx, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, smoke-tests/designer/wdio.conf.js
- Fix for conditions not working when a section name is added
=> FS-1250 Fix for conditions

.github/workflows/anchore-scan.yml
Tiny change to update the image name in `anchore-scan.yml` following refactor of workflows.
=> Fix anchor scan

runner/src/server/plugins/engine/views/partials/form.html
=> 🔍  Start page button "Start now" renamed to "Continue"

.github/workflows/dluhc-build-and-publish.yml
=> FS-1322 Upgrade version number to 0.1.2

runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/views/components/multiinputfield.html
- Fix for values displaying as undefined when returning to a form
http://localhost:3009/session/add-another
Body:
{
"metdata": {
"applicationId": "b"
},
"options": {               
"returnUrl": …
=> Fs 1428 add another return fix

runner/src/server/forms/currency-prefix-test.json, runner/src/server/plugins/engine/components/NumberField.ts
Added display of prefix (£) to number field when the prefix is present
=> FS-1431 - displaying prefix for number fields

.github/workflows/dluhc-build-and-publish.yml, runner/config/custom-environment-variables.json, runner/config/default.js, runner/src/server/plugins/basicAuth.ts, runner/src/server/plugins/engine/components/UkAddressField.ts, runner/src/server/plugins/engine/plugin.ts, runner/src/server/plugins/views.ts, runner/src/server/utils/configSchema.ts
Add basic auth strategy as an option toggled by basicAuthOn config var enabled by BASIC_AUTH_ON env var
=> FS-1433 Basic Auth Toggle

runner/src/server/plugins/engine/components/NumberField.ts, runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/views/partials/summary-row.html, runner/test/cases/server/plugins/engine/WebhookModel.test.ts
- Changed how the prefix is displayed. 
=> FS-1475 Fix for number fields not populating

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/components/UkAddressField.ts
Changed string splitting to use `' ` (added space to stop it getting added to values)
=> Fs 1509 postcode field

runner/src/server/plugins/engine/views/components/fileuploadfield.html
https://digital.dclg.gov.uk/jira/browse/FS-1479
=> fs-1479-added-text

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/views/404.html, runner/src/server/views/500.html
Updates 404 and 500 pages to replace FCDO specific content with COF content.
Note, I had to adapt the content slightly as we can't use any dynamic content on these pages.
=> BAU: update error pages

runner/src/server/forms/about-your-org.json, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
Updated render error method to use the supplied back link text and href
=> Updating error render method to use supplied back link

.github/workflows/dluhc-build-and-publish.yml
=> Forgot to inc version

runner/src/server/plugins/engine/components/UkAddressField.ts
- Fix for answers not populating on form data
Complete a form with the address component 
Revisit the same form 
From any page in the form click "Back to application overview" link
See the address field is populated …
=> Fs 1518 address fix

runner/src/server/plugins/engine/views/components/fileuploadfield.html, runner/src/server/views/partials/summary-row.html
https://digital.dclg.gov.uk/jira/browse/FS-1479
https://digital.dclg.gov.uk/jira/browse/FS-1575
=> fs-1479 added summary change and changed padding

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/views/partials/summary-row.html
Fix for accidentally merged change
=> Pushing fix for summary

runner/src/server/plugins/engine/components/DatePartsField.ts, runner/test/cases/server/plugins/engine/datepartsfield.test.ts, smoke-tests/designer/wdio.conf.js
- Validation on date parts no longer displays the website field error message.
- 
=> Fix for validation message

runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
- Address fields value is now sending correctly. Data manipulation has been done on the view model so the summary doest display a null
=> Address data fix

.github/workflows/dluhc-build-and-publish.yml
=> Upgrade version

.github/workflows/dluhc-build-and-publish.yml, model/src/data-model/types.ts, runner/src/server/forms/add-another.json, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/views/partials/form.html
- Added feature to add and title and customise the column names
=> Title and columns can now be customised

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/views/partials/form.html
Add another button text change to match prototype
=> Add another button text change

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/services/cacheService.ts
Update cacheService to use VCAP_SERVICES redis uri
=> FS-1638 Update cacheService to use VCAP_SERVICES redis uri

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/services/cacheService.ts
Enable Catbox Provider to use VCAP_SERVICES uri host instead of REDIS_HOST env var
=> FS-1638 add vcap services redis support

.github/workflows/dluhc-build-and-publish.yml, runner/config/custom-environment-variables.json
Parse string BASIC_AUTH_ON env var as boolean
=> FIX basic auth env var

runner/src/server/forms/about-your-org.json, runner/src/server/plugins/engine/components/DatePartsField.ts, runner/src/server/plugins/engine/components/FileUploadField.ts, runner/src/server/plugins/engine/components/UkAddressField.ts, runner/src/server/plugins/engine/components/YesNoField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/views/components/fileuploadfield.html, runner/src/server/plugins/engine/views/partials/form.html, runner/src/server/views/partials/summary-detail.html, runner/src/server/views/partials/summary-row.html, runner/src/server/views/summary.html, runner/test/cases/server/plugins/engine/WebhookModel.test.ts, runner/test/cases/server/plugins/engine/WelshSummaryViewModel.json
- Fixing components for welsh translations. (The if statements will eventually be removed when localisation is implemented)
=> Fs 1799 welsh components

runner/src/server/services/uploadService.ts
- Added welsh check for encoding welsh special characters 
=> Fs 1998 upload bug

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/services/uploadService.ts
=> fix file upload issue

runner/src/server/plugins/engine/components/MultilineTextField.ts, runner/src/server/plugins/engine/components/TextField.ts, runner/src/server/plugins/engine/views/components/multiinputfield.html, smoke-tests/designer/wdio.conf.js
- The hint text is now set to the label to avoid accessibility issues. This change avoids making changes to the forms themselves
- There should be a label for now attached to the filed instead of just a hint
=> Fix for screen reader issue

.github/workflows/dluhc-build-and-publish.yml
=> bumping version

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/views/partials/form.html
- Add a label for screen readers to help users with visibility issues
=> FS-2197 Add hidden label

.github/workflows/dluhc-build-and-publish.yml, runner/src/client/sass/application.scss
- fixing padding on the head classes
=> Adding padding class

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- Fix for add another removing form_seesion_identifier. Added to do for later date improvement.
- Go to an add another section
- add another
- Url should keep the form_session_identifier
- Should no longer crash
=> Fs 2311 add another fix

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- Remove link did keep the form session identifier 
- Go to add another section
- Add another
- removed the add values and the state should stay the same
=> Add another remove fix

.github/workflows/dluhc-build-and-publish.yml, runner/config/default.js, runner/src/server/forms/test.json, runner/src/server/plugins/applicationStatus.ts, smoke-tests/designer/wdio.conf.js
Submission of form wasn't happening if there wasn't a confirmation model or return url. For should now submit declaration correctly
- Navigate to https://webhook.site/ to see the post and put requests for save per page and form submission
- Copy the url into the savePerPageUrl in the test.json form
- Go through the test form and hit submit on the summary page, you should see a final post request after the declaration has been has been submitted
- Also complete a section using the docker to see if this hasn't changed, save per page/submission
=> Fs 2431 save url

.github/workflows/dluhc-build-and-publish.yml
- Adding write permission the fix the taging workflow
=> Adding contents write permission

fsd_config/manifest.yml
Jira ticket:
https://digital.dclg.gov.uk/jira/browse/FS-2422
- Added health-check-invocation-timeout: 10 to the manifest file to increase the Cloud foundry runs healthchecks timeout limit (currently at 1 second) to 10 seconds on Dev and Test env. As having it at 1 second sometimes disrupted the e2e tests running against Dev and Test due to the running app restarting because of the healthchecks. 
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#health-check-invocation-timeout …
=> FS-2422: Add health check invocation timeout for Forms microservice 

fsd_config/form_jsons/cof_r2/cy/cyllid-sydd-ei-angen.json, fsd_config/form_jsons/cof_r2/en/funding-required.json
https://digital.dclg.gov.uk/jira/browse/FS-2389
Fixed the missing label for `Capital Funding`  & `Revenue Funding` elements
=> fixed the missing label for NumberFields

runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
Only replace new lines if the value actually exists, otherwise we get a NPE on empty entries.
=> BAU: Only replace new lines if value exists

.github/workflows/dluhc-build-and-publish.yml
=> BAU: Bump runner version

.github/workflows/dluhc-build-and-publish.yml
=> BAU: Bump version

runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html
Adds missing hint on client side upload field.
=> FS-2421: Add hint

.github/workflows/dluhc-build-and-publish.yml
Bump version cause I forgot, for the fourth time...
=> FS-2421: Bump version

.github/workflows/dluhc-build-and-publish.yml, model/src/components/types.ts, runner/src/server/forms/report-a-terrorist.json, runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html
- Add filesize base of 1024 so sizes show properly
- Show label instead of page title on error messages
- Add totalOverallFilesize option for configurability
- Show (optional) text if no file uploads are required
=> BAU: Quality of life bug fixes file upload

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r2/cy/costau'r-prosiect.json, fsd_config/form_jsons/cof_r2/cy/cyllid-sydd-ei-angen.json, fsd_config/form_jsons/cof_r2/en/funding-required.json, fsd_config/form_jsons/cof_r2/en/project-costs.json, model/src/data-model/types.ts, runner/src/server/forms/add-another-samepage.json, runner/src/server/forms/add-another-seperatepage.json, runner/src/server/forms/add-another.json, runner/src/server/plugins/engine/components/MultiInputField.ts, runner/src/server/plugins/engine/components/SelectionControlField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/models/types.ts, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/views/components/multiinputfield.html, runner/src/server/plugins/engine/views/partials/form.html, runner/src/server/views/repeating-summary.html
- Add another now works with mulitple component types
This also redirects and fixes the separate page functionality.
The children components are now defined in the form json
```
{
"name": "MultiInputField",
"options": {
"prefix": "£",
"columnTitles": ["Title", "Cost", "Link"]
},
"type": "MultiInputField",
"title": "MultiInputField",
"hint": "The MultiInputField needed",
"schema": {},
"children": [
{
"type": "TextField",
"name": "type-of-revenue-cost",
"title": "Type of Revenue Cost",
"schema": {},
"options": {}
},
{
"type": "NumberField",
"name": "Cost", …
```
=> Add another changes

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r2/cy/costau'r-prosiect.json, fsd_config/form_jsons/cof_r2/en/project-costs.json, runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts
- Titles should now display on same page functionality and changed repeated ids
=> Fixing titles and repeated ids

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r2/cy/costau'r-prosiect.json, fsd_config/form_jsons/cof_r2/cy/cyllid-sydd-ei-angen.json, fsd_config/form_jsons/cof_r2/en/funding-required.json, fsd_config/form_jsons/cof_r2/en/project-costs.json
- Ordered ids causing ordered tables issue, add back the class to match prototype
=> Add another fixes

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/applicant-information-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/asset-information-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/community-benefits-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/community-engagement-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/community-representation-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/community-use-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/environmental-sustainability-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/feasibility-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/final-confirmations-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/funding-required-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/inclusiveness-and-integration-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/operational-costs-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/project-information-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/project-qualifications-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/risk-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/skills-and-resources-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/upload-business-plan-cof-r3-w1.json
- Summary route path was not named correctly in the forms which was causing issues returning to summary 
=> Fix summary route on forms

.github/workflows/dluhc-build-and-publish.yml, smoke-tests/designer/features/components/formPage.component.js, smoke-tests/designer/features/pageobjects/pages/formRunner.page.js
- Fix to stabilise the inconsistent smoke test failing 
=> Fix for inconsistent failing smoke test

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/test/cases/server/titles.test.js
- Removed the single component check so that the title of the components will be displayed on the forms
=> Removing single form component title removal

fsd_config/form_jsons/cof_r3/en/asset-information-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/organisation-information-cof-r3-w1.json, runner/src/server/plugins/engine/components/UkAddressField.ts
- Changing multiple text filed sizes to match the prototype
=> Changing text field sizes to match prototype

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/organisation-information-cof-r3-w1.json
- Removed space between title and hint 
- Removing other from title 
-Corrected website field to a hint
- Question is now within its section
=> Changes to organisation information

fsd_config/form_jsons/cof_r3/en/inclusiveness-and-integration-cof-r3-w1.json
The following bullet points have been removed from the Inclusiveness and integration form landing page:
how you'll make your project accessible to everyone
how the project will bring the community together
- [✅] My changes do not introduce any new linting errors
- [✅] I have performed a self-review of my own code
- [✅] My changes generate no new warnings
- [✅] New and existing unit tests pass locally with my changes
- [✅] I have checked deployments are working in all environments
=> fs-2758-remove-bullet-points

.github/workflows/dluhc-build-and-publish.yml
=> bump version

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/funding-required-cof-r3-w1.json
[- Form runner - Help with management case text doesn't match prototype](https://digital.dclg.gov.uk/jira/browse/FS-2816)
- [Form runner - Text changes in Funding required form](https://digital.dclg.gov.uk/jira/browse/FS-2817)
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the …
=> Updating funding form

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/asset-information-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/risk-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/upload-business-plan-cof-r3-w1.json
- Increasing file size to 10mb
=> Increasing file size to 10 mb

.github/workflows/dluhc-build-and-publish.yml, model/src/components/types.ts, runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts, runner/src/server/views/partials/summary-row.html
- If no files provided, and optional, show "Not supplied"
- If optional, then we render (optional) on the form itself
- Bump version to 0.1.79 (one higher than https://github.com/communitiesuk/digital-form-builder/pull/187)
- Check out this branch
- Start your local `nodemon` instance of the form runner
- You need to have `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` env vars
- I am using the ones from the `form-runner-dev` service on sandbox
- `cf t -s sandbox && cf service-key form-uploads-dev local-testing`
- Generate a session token with relevant application id & form session identifier
```bash
curl --location 'http://127.0.0.1:3009/session/report-a-terrorist' \
--header 'Content-Type: application/json' \
--data '{
"options": {},
"metadata": {
"application_id": "tferns-fs2759", …
```
=> FS-2759: Show (optional) text & "Not supplied"

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/views/partials/summary-row.html
=> FS-2759: Fix spelling error on summary

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/funding-required-cof-r3-w1.json
- Changing and line with details in the funding required for from "your full project costs" to "your full operational costs" to match prototype 
=> Changing text within details in fuding required

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- Remove will now now longer cause a 500 error on add another pages
https://digital.dclg.gov.uk/jira/browse/FS-2861
=> Fix remove causing a 500 error 

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/organisation-information-cof-r3-w1.json
- Updating purpose form to remove repeated titles
=> Updating form

.github/workflows/dluhc-build-and-publish.yml, fsd_config/config/production.json
=> BAU: Change feedback to R3W1

fsd_config/form_jsons/night_shelter/objectives-and-activities-ns.json
- Changing for heading to match the prototype 
=> Updating form to match prototype

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/views/repeating-summary.html
- Option fields on Multi input componets will now display Not Supplied instead of null
=> Optional feilds will now display not supplied

fsd_config/form_jsons/night_shelter/organisation-type-ns.json, model/src/components/types.ts, runner/src/server/plugins/engine/components/CheckboxesField.ts
- Added a change so that check box fields can take a divider option. Orgainisation types now macthes prototype 
=> List divider

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/cy/gwybodaeth-am-y-sefydliad-cof-r3-w1.json
- Path was missing `-arall` on the end, meaning the form runner would hang indefinitely...
=> FS-2701: Corrects missing path on form

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/components/CheckboxesField.ts
=> Checkbox bug fix

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/cy/buddion-cymunedol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cadarnhadau-terfynol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cefnogaeth-leol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/costau-gweithredol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cyllid-sydd-ei-angen-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cymhwysedd-y-prosiect-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cynaliadwyedd-amgylcheddol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cynhwysiant-ac-integreiddio-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/cynrychiolaeth-gymunedol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/defnydd-cymunedol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/dichonoldeb-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/gwybodaeth-am-y-prosiect-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/gwybodaeth-am-y-sefydliad-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/gwybodaeth-am-yr-ased-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/lanlwythwch-y-cynllun-busnes-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/risg-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/sgiliau-ac-adnoddau-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/ymgysylltiad-cymunedol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json
- Add isWelsh metadata to all forms
- Fix supporting evidence translation
- Fix Does your project meet the definition of a subsidy translation
- Change 5MB -> 10MB for r3w1
- Add (optional) text for local support on both welsh/english forms
=> BAU: Welsh fixes

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/cy/cefnogaeth-leol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/gwybodaeth-am-y-sefydliad-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/organisation-information-cof-r3-w1.json, runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts
- Bump version
- Translate some optional fields
- Allow optionalText override on ClientSide file upload
- Capitalise and translate (Other)
=> BAU: Fix some issues on Welsh forms

fsd_config/form_jsons/night_shelter/working-in-partnership-ns.json
- Changing wording to match the prototype 
=> Changing intro text to match prototype

fsd_config/form_jsons/night_shelter/organisation-type-ns.json
- Title on summary now matches prototype
=> Change title to match prototype

fsd_config/form_jsons/night_shelter/building-works-ns.json
- Fixing route for is the building listed question, selecting no will now take the user to the summary page.
- https://digital.dclg.gov.uk/jira/browse/FS-2860
=> Fixing route for is building listed

fsd_config/form_jsons/night_shelter/local-need-and-support-ns.json
- Changing title to match the prototype in the local need and support form
https://digital.dclg.gov.uk/jira/browse/FS-2852
=> Updating title to match the prototype

runner/src/server/plugins/engine/components/MultiInputField.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- YesNo field no long displays true of false for multiput fields. Have also fixed the summary page
=> YesNoField no long displays true/false

fsd_config/form_jsons/night_shelter/name-your-application-ns.json
- Text input width now matching prototype
https://digital.dclg.gov.uk/jira/browse/FS-2893
=> Change text input width to match prototype

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/cy/cefnogaeth-leol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json, runner/src/server/plugins/engine/components/DatePartsField.ts, runner/src/server/plugins/engine/components/DateTimePartsField.ts, runner/src/server/plugins/engine/components/FormComponent.ts, runner/src/server/plugins/engine/components/MonthYearField.ts, runner/src/server/plugins/engine/components/MultiInputField.ts, runner/src/server/plugins/engine/components/constants.ts
https://digital.dclg.gov.uk/jira/browse/FS-2937
Added "(optional)" text translation for welsh
=> add optional text rendering for welsh

fsd_config/form_jsons/night_shelter/funding-required-ns.json
- Changing hint text in the funding required form to match the prototype
https://digital.dclg.gov.uk/jira/browse/FS-2920
=> Changing hint text to match the prototype

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/organisation-type-ns.json
- Summary route was incorrect on the organisation type route
=> Fixing summary route

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/current-services-ns.json
- Routes are now fixed for "Which day provision services are you currently providing?" and "Who do you currently provide targeted specialist support to?"
https://digital.dclg.gov.uk/jira/browse/FS-2864
=> Fs 2864 fixing routes

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/cy/cefnogaeth-leol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/cy/gwybodaeth-am-y-prosiect-cof-r3-w1.json, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json
https://digital.dclg.gov.uk/jira/browse/FS-2944
- minor welsh fixes
=> welsh fixes

.github/workflows/dluhc-build-and-publish.yml
https://github.com/communitiesuk/digital-form-builder/actions/runs/5186235998/jobs/9347308311
Bumping runner as tagging failed on main.
=> BAU: Bump version of runner

fsd_config/form_jsons/night_shelter/building-works-ns.json
remove references to rtf for fil upload
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My changes do not introduce any new linting errors
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation and versioning
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally …
=> fs-2950-remove-rtf

runner/config/default.js, runner/src/server/views/404.html, runner/src/server/views/500.html
https://digital.dclg.gov.uk/jira/browse/FS-2913
Fixed default service name & email
=> remove COF from defaults

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts, runner/test/cases/server/plugins/router.test.ts
https://digital.dclg.gov.uk/jira/browse/FS-2963
https://digital.dclg.gov.uk/jira/browse/FS-2843
Make feedback link dynamic
Linked PR'S https://github.com/communitiesuk/funding-service-design-frontend/pull/348
=> make feedback link dynamic

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/joint-applications-ns.json, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- Fixing undefined remove text error
=> Fixing removetext error

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/current-services-ns.json, fsd_config/form_jsons/night_shelter/project-milestones-ns.json
Following https://github.com/communitiesuk/digital-form-builder/pull/242
We need to specify `MonthYearField`(s) as required.
=> FS-2952: Set month year fields to required

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/building-works-ns.json, model/src/components/types.ts, runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
- Add `noReturnUrlOnSummaryPage` option & add to single form
=> BAU: noReturnUrlOnSummaryPage 

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/staff-and-volunteers-ns.json
Adding precision to number field so it can input 1 decimal place
=> Add precision number

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/components/NumberField.ts
Decimals now correctly work for the number field
=> Decimals now correctly work for the number field

README_DLUHC.md, runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts, runner/src/server/plugins/engine/components/types.ts, runner/src/server/plugins/engine/pageControllers/validationOptions.ts, runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html
Updated clientSideUploadField to display the title text in the error message, but not duplicate that title when `hideTitle` is true
Locally in the docker runner - for both NTSF and COF
=> Fs 2862 upload error msg

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
- Adding null check to no longer display null on the title page when changing a answer with a new route
=> Adding null check for iteration

fsd_config/manifest.yml, runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
https://digital.dclg.gov.uk/jira/browse/FS-2977
https://digital.dclg.gov.uk/jira/browse/FS-2979
- Made contact us page dynamic for the fund
- Made privacy link dynamic for the fund
=> FS-2977-make-contact-us-page-dynamic-for-fund

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/components/MonthYearField.ts, runner/src/server/plugins/router.ts, runner/src/server/views/layout.html
https://digital.dclg.gov.uk/jira/browse/FS-2977
https://digital.dclg.gov.uk/jira/browse/FS-2979
Follow up for previous PR https://github.com/communitiesuk/digital-form-builder/pull/250
- Remove hardcoded privacy link
=> remove hard coded privacy link

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/building-works-ns.json
- Removing dupe title to match prototype 
=> Removing dupe title

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- Adding the back link to the add another summary page
=> Fs 2998 repeating page backlink

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/night_shelter/building-works-ns.json
- Updated question "Give a brief summary of the advice you received" to match the prototype https://digital.dclg.gov.uk/jira/browse/FS-2999
=> Fs 2999 update building works question

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/views/repeating-summary.html
- Multi input field seperate table will now align with the back link
=> Adding corrent class to div to align

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3/en/local-support-cof-r3-w1.json
- Optional text has now been added back for cof r3 local support form
=> Adding back optional text that was removed due

fsd_config/Dockerfile
=> cof-r3w2-config-patch-2

fsd_config/form_jsons/cof_r3w2/cy/costau-gweithredol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/cy/cyllid-sydd-ei-angen-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ased-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/en/asset-information-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/en/funding-required-cof-r3-w2.json
=> cof-r3w2-patch-3

.github/workflows/dluhc-build-and-deploy-with-forms.yml
Double sets of steps and runs-on
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ N/A ] New feature (non-breaking change which adds functionality)
- [ N/A ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ N/A ] This change requires a documentation update
- [ X ] My changes do not introduce any new linting errors
- [ X ] I have performed a self-review of my own code
- [ N/A ] I have commented my code, particularly in hard-to-understand areas
- [ N/A ] I have made corresponding changes to the documentation and versioning
- [ N/A ] My changes generate no new warnings
- [ N/A ] I have added tests that prove my fix is effective or that my feature works
- [ N/A ] New and existing unit …
=> Fixing duplicate action workflow instructions

fsd_config/form_jsons/cof_r3w2/cy/costau-gweithredol-cof-r3-w1.json
=> cof-config-cof-r3w2-patch-4

fsd_config/form_jsons/cof_r3w2/cy/costau-gweithredol-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/cy/cyllid-sydd-ei-angen-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ymgeisydd-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/en/funding-required-cof-r3-w2.json
=> cof-r3w2-config-patch-5

fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ased-cof-r3-w1.json, fsd_config/form_jsons/cof_r3w2/en/asset-information-cof-r3-w2.json
=> cof-r3w2-config-patch-6

.github/workflows/dluhc-build-and-publish.yml
=> cofr3w2-config-bump-version

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ased-cof-r3-w1.json
=> cof-r3w2-config-patch-7

.github/workflows/dluhc-build-and-publish.yml
- Bump version as main has duplicate atm
=> FS-3348: Bump version

fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ased-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/en/asset-information-cof-r3-w2.json
=> cof-r3w2-config-patch-9

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3w2/cy/cyllid-sydd-ei-angen-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ased-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/en/funding-required-cof-r3-w2.json, smoke-tests/designer/wdio.conf.js
- Fix the 404 issues that was occurring on the welsh asset information form
=> Fixing the path for assest information

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof_r3w2/cy/cyllid-sydd-ei-angen-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/cy/gwybodaeth-am-yr-ased-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/en/asset-information-cof-r3-w2.json, fsd_config/form_jsons/cof_r3w2/en/funding-required-cof-r3-w2.json
https://dluhcdigital.atlassian.net/browse/FS-3372
https://dluhcdigital.atlassian.net/browse/FS-3393
- Adding line break to help with management cases
- Removing hint text from FreeTextField component in asset Info
=> Multiple form changes

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/applicant-information-cyp.json, fsd_config/form_jsons/cyp_r1/application-name-cyp.json, fsd_config/form_jsons/cyp_r1/declarations-cyp.json, fsd_config/form_jsons/cyp_r1/existing-work-cyp.json, fsd_config/form_jsons/cyp_r1/location-of-activities-cyp.json, fsd_config/form_jsons/cyp_r1/objectives-and-activities-cyp.json, fsd_config/form_jsons/cyp_r1/organisation-information-cyp.json, fsd_config/form_jsons/cyp_r1/outputs-and-outcomes-cyp.json, fsd_config/form_jsons/cyp_r1/project-milestones-cyp.json, fsd_config/form_jsons/cyp_r1/risk-and-deliverability-cyp.json, fsd_config/form_jsons/cyp_r1/skills-and-experience-cyp.json, fsd_config/form_jsons/cyp_r1/value-for-money-cyp.json, fsd_config/form_jsons/cyp_r1/working-with-fund-beneficiaries-cyp.json, runner/src/server/plugins/engine/components/WebsiteField.ts, runner/src/server/plugins/engine/views/components/multiinputfield.html
- Fixing issue with the current forms.
- Fixing build issue with website field when using within MultiInputField
=> Pushing form changes for build fix

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/organisation-information-cyp.json, runner/src/server/plugins/engine/components/MultiInputField.ts, runner/src/server/plugins/engine/components/WebsiteField.ts, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/views/components/multiinputfield.html
- MultiInput field can now use Website fields and UkAdressFields
=> Fix for MultiInput field to use website fields and uk address fields.

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/applicant-information-cyp.json, fsd_config/form_jsons/cyp_r1/application-name-cyp.json, fsd_config/form_jsons/cyp_r1/location-of-activities-cyp.json, fsd_config/form_jsons/cyp_r1/objectives-and-activities-cyp.json, fsd_config/form_jsons/cyp_r1/organisation-information-cyp.json, fsd_config/form_jsons/cyp_r1/project-milestones-cyp.json, fsd_config/form_jsons/cyp_r1/risk-and-deliverability-cyp.json, fsd_config/form_jsons/cyp_r1/skills-and-experience-cyp.json, fsd_config/form_jsons/cyp_r1/value-for-money-cyp.json
=> cyp-config

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/objectives-and-activities-cyp.json
This PR resolves the below issue
`2023-09-20T12:54:14.00+0100 [APP/PROC/WEB/0] ERR TypeError: Cannot read property 'max' of undefined
2023-09-20T12:54:14.00+0100 [APP/PROC/WEB/0] ERR at new FreeTextField (/usr/src/app/runner/dist/server/plugins/engine/components/FreeTextField.js:57:20)
2023-09-20T12:54:14.00+0100 [APP/PROC/WEB/0] ERR at /usr/src/app/runner/dist/server/plugins/engine/components/ComponentCollection.js:32:14
2023-09-20T12:54:14.00+0100 [APP/PROC/WEB/0] ERR at Array.map (<anonymous>)
2023-09-20T12:54:14.00+0100 [APP/PROC/WEB/0] ERR at new ComponentCollection (/usr/src/app/runner/dist/server/plugins/engine/components/ComponentCollection.js:25:38)
2023-09-20T12:54:14.00+0100 [APP/PROC/WEB/0] ERR at new MultiInputField (/usr/src/app/runner/dist/server/plugins/engine/components/Mu …
=> BAU: Fix error in objectives and activities cyp form add another question

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/applicant-information-cyp.json, fsd_config/form_jsons/cyp_r1/organisation-information-cyp.json
https://dluhcdigital.atlassian.net/browse/FS-3492
https://dluhcdigital.atlassian.net/browse/FS-3495
https://dluhcdigital.atlassian.net/browse/FS-3498
- Changes to prototype to match forms
=> Changes to forms to match prototypes 

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
Form runner - Add another entries in the table view are displayed in bold
https://dluhcdigital.atlassian.net/browse/FS-3488
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> remove bold in first column values

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/applicant-information-cyp.json, fsd_config/form_jsons/cyp_r1/application-name-cyp.json, fsd_config/form_jsons/cyp_r1/declarations-cyp.json, fsd_config/form_jsons/cyp_r1/existing-work-cyp.json, fsd_config/form_jsons/cyp_r1/location-of-activities-cyp.json, fsd_config/form_jsons/cyp_r1/objectives-and-activities-cyp.json, fsd_config/form_jsons/cyp_r1/organisation-information-cyp.json, fsd_config/form_jsons/cyp_r1/outputs-and-outcomes-cyp.json, fsd_config/form_jsons/cyp_r1/project-milestones-cyp.json, fsd_config/form_jsons/cyp_r1/risk-and-deliverability-cyp.json, fsd_config/form_jsons/cyp_r1/skills-and-experience-cyp.json, fsd_config/form_jsons/cyp_r1/value-for-money-cyp.json, fsd_config/form_jsons/cyp_r1/working-with-fund-beneficiaries-cyp.json
Form runner - Fund name for CYP not displaying in form pages
https://dluhcdigital.atlassian.net/browse/FS-3476
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> add fund name to forms

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/about-your-organisation-cyp.json, fsd_config/form_jsons/cyp_r1/location-of-activities-cyp.json, fsd_config/form_jsons/cyp_r1/value-for-money-cyp.json, runner/src/server/plugins/engine/components/UkAddressField.ts
https://dluhcdigital.atlassian.net/browse/FS-3494
https://dluhcdigital.atlassian.net/browse/FS-3507
https://dluhcdigital.atlassian.net/browse/FS-3502
https://dluhcdigital.atlassian.net/browse/FS-3504
- Fix for the details section in the about your organisation form to match prototype
- Added to correct section for value for money forms
- Hide Title on value for monet question
Before …
=> Fix for about your org form details section and wrong section for value for money

fsd_config/form_jsons/cyp_r1/name-your-application-cyp.json
Updating spacing in name your application to match the mural
=> fs-3493 spacing in name your application hint

fsd_config/form_jsons/cyp_r1/value-for-money-cyp.json
Updating start date in value for money form to 27th September 2023
=> fs-3520 update start date to 27 sept

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/risk-and-deliverability-cyp.json
- Changes for risks and deliverability 
=> Updating risk and deliverabilty

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/models/viewModel.ts, runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
=> Fix for empty optional components

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/outputs-and-outcomes-cyp.json
- Removed the s from hong kong nationals
=> Hong Kong text change

fsd_config/form_jsons/cyp_r1/about-your-organisation-cyp.json, fsd_config/form_jsons/cyp_r1/applicant-information-cyp.json, fsd_config/form_jsons/cyp_r1/location-of-activities-cyp.json, fsd_config/form_jsons/cyp_r1/name-your-application-cyp.json, fsd_config/form_jsons/cyp_r1/outputs-and-outcomes-cyp.json, fsd_config/form_jsons/cyp_r1/project-milestones-cyp.json, fsd_config/form_jsons/cyp_r1/risk-and-deliverability-cyp.json, fsd_config/form_jsons/cyp_r1/skills-and-experience-cyp.json, fsd_config/form_jsons/cyp_r1/value-for-money-cyp.json
Addresses the following styling bugs:
- FS-3508
- FS-3501
- FS-3499
- FS-3513
- FS-3523
=> CYP styling and spelling corrections

.github/workflows/dluhc-build-and-publish.yml, fsd_config/Dockerfile
=> Fixing path for the DPI forms

runner/src/server/plugins/engine/views/components/multiinputfield.html
Adding title to print above a UkAddressField when it is part of a multi input field
=> fs-3545 Adding heading to address field when part of multi input

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpi_r2/dataset-information-dpi.json, fsd_config/form_jsons/dpi_r2/declarations-dpi.json, fsd_config/form_jsons/dpi_r2/engaging-the-odp-community-dpi.json, fsd_config/form_jsons/dpi_r2/engaging-the-organisation-dpi.json, fsd_config/form_jsons/dpi_r2/future-work-dpi.json, fsd_config/form_jsons/dpi_r2/organisation-information-dpi.json, fsd_config/form_jsons/dpi_r2/roles-and-recruitment-dpi.json, fsd_config/form_jsons/dpi_r2/your-skills-and-experience-dpi.json, fsd_config/form_jsons/generic/name-your-application.json, runner/src/server/forms/test.json
- Fixing the title on all Forms
- fixing summary behaviour on name your application 
=> FS 3561 Fixing title and summary link

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts, runner/src/server/plugins/engine/pageControllers/index.ts, runner/src/server/views/repeating-summary.html
- Reverting changes to try and fix exception being thrown on add another
=> Bau revert add another fix

runner/src/server/views/repeating-summary.html
=> BAU: Fix crumb issue

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpi_r2/dataset-information-dpi.json
- Conditions for the "Which datasets have you collected?" question should now lead to there correct pages. this will stop the tree preservation page also showing/
=> FS-3590 - Fixing conditions for data sets

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpi_r2/engaging-the-odp-community-dpi.json, fsd_config/form_jsons/dpi_r2/roles-and-recruitment-dpi.json, fsd_config/form_jsons/dpi_r2/your-skills-and-experience-dpi.json
https://dluhcdigital.atlassian.net/browse/FS-3558
https://dluhcdigital.atlassian.net/browse/FS-3557
https://dluhcdigital.atlassian.net/browse/FS-3555
https://dluhcdigital.atlassian.net/browse/FS-3559
- Change to the skill and experience form to match prototype
- Change for a question on the same form
- Changing casing on open digital planning 
- Change to backfill order question
Before …
=> FS 3558 Mulitple form Changes 

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpi_r2/your-skills-and-experience-dpi.json
- Changing about this section bullet point
=> FS-3609 Change to about this section bullet point

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpif_r2/dataset-information-dpi.json, fsd_config/form_jsons/dpif_r2/declarations-dpi.json, fsd_config/form_jsons/dpif_r2/engaging-the-odp-community-dpi.json, fsd_config/form_jsons/dpif_r2/engaging-the-organisation-dpi.json, fsd_config/form_jsons/dpif_r2/future-work-dpi.json, fsd_config/form_jsons/dpif_r2/organisation-information-dpi.json, fsd_config/form_jsons/dpif_r2/roles-and-recruitment-dpi.json, fsd_config/form_jsons/dpif_r2/your-skills-and-experience-dpi.json, fsd_config/form_jsons/generic/name-your-application.json
- Change to form titles to match the new links from the new link tree
=> FS 3620 Updating titles to match links

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpif_r2/dataset-information-dpi.json
- Change to dataset info form, adding a space
=> Adding space

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpif_r2/declarations-dpi.json
- Changing section 151 officer to lower case
=> Change to section 151 officer

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpif_r2/future-work-dpi.json
- Change to future work dpi form, capitalised BOPS acronym
=> Updated casing for Back Office Planning System

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpif_r2/your-skills-and-experience-dpi.json
- Change to in this section text in your skills and experience
=> FS 3628 Change to in this section text in your skills and experience

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/dpif_r2/roles-and-recruitment-dpi.json
- Changes to roles and recruitment about this section to match prototype
=> FS-3632 Changes to roles section

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/views/404.html
=> BAU: Remove hardcoded COF on 404

.github/workflows/dluhc-build-and-publish.yml, runner/src/server/plugins/engine/models/viewModel.ts, runner/test/cases/server/plugins/engine/WebhookModel.test.ts
- Added "(optional)" in "About your organisation"
- Added "(optional)" in "Applicant information"
=> Optional displayed in summary

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/about-your-organisation-cyp.json
- Updated remove text to say Delete in "Website and social media"
=> Updated remove text for website and social media

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cyp_r1/skills-and-experience-cyp.json
- Question on the page should now match on the error and summary page 
- 
=> Updating title to match the Question on the page 

fsd_config/form_jsons/cof/en/asset-information-cof.json
- Changing the routing in the new sections to match the prototype 
=> BAU updating routing for asset information

.github/workflows/dluhc-build-and-publish.yml, fsd_config/form_jsons/cof/en/asset-information-cof.json
- Adding workflow dispatch for manual trigger
=> BAU Adding workflow dispatch for manual trigger

.github/workflows/copilot_deploy.yml
* Added in ignore files
* Removed the build pipeline to stop duplicates (build pipeline already runs on push)
+ref: BAU
+semver: minor
=> Removed Docker Build

fsd_config/Dockerfile
- The folder was included in the mount for the form builder meaning the folder path was never find. This fixs this issue and docker will now work with windows again
- 
=> BAU - Fix for COPY not finding for folder on windows

fsd_config/form_jsons/cof/eoi/cof-eoi-asset.json, runner/src/server/forms/test.json, runner/src/server/plugins/engine/models/FormModel.ts
Updated public authpority question to match the mural and removed trailing space from value
=> Bau update eoi public auth

.github/workflows/copilot_deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-4078
Add the VERSION env parameter back in from how it was when we deployed to PaaS.
- [n/a] New feature (non-breaking change which adds functionality)
- [n/a] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [n/a] This change requires a documentation update
=> FS-4078 - Re-include VERSION in env

.github/workflows/anchore-scan.yml
Add a workflow to allow branch runs
=> BAU - add workflow

fsd_config/form_jsons/cof/eoi/cof-eoi-declaration.json
- Updating the cof-eoi-declaration forms
=> Updating EOI declarations form

fsd_config/form_jsons/cof/eoi/cof-eoi-funding.json
- Putting the hint inside of a label to fix accessibility issue
=> FS-4081: Add accessibility label

fsd_config/form_jsons/cof/eoi/cof-eoi-funding.json
Added missing checkbox and updated associated conditions
=> fs-4111 adding checkbox and conditions

fsd_config/form_jsons/cof/eoi/development-support-provider.json
- Fixing the list on the change to development for to match the mural
=> FS-4117 - Change to development form

fsd_config/form_jsons/cof/cy/gwybodaeth-am-yr-ased-cof.json, fsd_config/form_jsons/cof/en/asset-information-cof.json
https://dluhcdigital.atlassian.net/browse/FS-4269
Fixed bug - file upload not showing for `Upload asset valuation or lease agreement` question
=> updated asset forms r4w1

runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html
Fix the after upload done change is selected upload is not working 
=> FS-3988 quick fix button check

copilot/fsd-form-runner/manifest.yml
=> Fs 4573 stop form runner

copilot/fsd-form-runner/manifest.yml
Adding instance count to match {min}-{max} and in the main we have 0-0 instances since we are planing to shutdown the service
=> fix manifest.yml
