communitiesuk/digital-form-builder

- runner/src/server/forms/add-another.json
- runner/src/server/plugins/engine/components/MultiInputField.ts
- runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts
- runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- runner/src/server/plugins/engine/views/partials/form.html
- runner/src/server/views/summary.html
- The add another functionality, now works on a single page
- Titles for the fields should now also be customisable.
https://user-images.githubusercontent.com/97108643/182178179-a0928a3f-1f71-4b31-b204-946d1d35005e.mov
applicable. To flag the change to QA assign **@XGovFormBuilder/qa** as one of the …
> Add another changes

- runner/src/server/plugins/applicationStatus.ts
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
The implementation of the return URL is blocking the callback URL webhook to PUT form data. 
- The return Url redirect has been moved to after the callback urls/webhooks have run.
- Bug fix (non-breaking change which fixes an issue)
> Fix redirect hook

- runner/src/server/plugins/applicationStatus.ts
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
Description
After a form submission the state associated to the forms session is changed to record the submission, this prevents returning to the form via the return url on form submission. It prevents a user changing the answer on their forms within the session's duration.
Now checks to see if a return Url has been specified (on subsequent requests), if so use this return url.
Type of change
Bug fix (non-breaking change which fixes an issue)
> Fix allow multiple form rehydrates

- runner/src/server/services/statusService.ts
In response to an Issue raised on: https://github.com/communitiesuk/funding-service-design-frontend/pull/99
[FSD frontend](https://github.com/communitiesuk/funding-service-design-frontend) COPYs the [forms jsons ](https://github.com/communitiesuk/funding-service-design-frontend/tree/main/form_jsons/public)onto the form runner container as part of the [DOCKER file workflow](https://github.com/communitiesuk/funding-service-design-frontend/blob/main/Dockerfile#:~:text=COPY%20./form_jsons/public,config/*%20runner/config/), called in [this action](https://github.com/communitiesuk/funding-service-design-frontend/blob/077f1ed906850ef377642c38ffe8be5097a03bf1/.github/workflows/build-deploy-forms.yml#L45:~:text=push%3A%20true-,file%3A%20Dockerfile,-build%2Dargs%3A).
However the form jsons …
> Allow save per page config on rehydration

- runner/src/server/plugins/engine/components/TextField.ts
- runner/src/server/plugins/engine/components/UkAddressField.ts
- runner/test/cases/server/plugins/engine/components/TextField.test.ts
Adds regex validation of postcode in UK address field (and fix it more widely for `textinput` fields.
- [ X ] New feature (non-breaking change which adds functionality)
Tested locally on designer/runner. Tested regex using regex tester
Updated unit tests
> FS-1386: add regex to postcode

- runner/src/server/plugins/engine/components/UkAddressField.ts
_Small follow-up to #33 fixing issue reported by @rayhan15243_ 
Change regex to be case-insensitive
Tested manually against regex validator e.g. https://regex101.com/r/2ZT6Of/1
(Would like to write unit tests for the UK Address Component but haven't got my environment set up for this)
> FS-1386: use case insensitive postcode regex

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/services/uploadService.ts
Previously the answer for file uploads was hardcoded to the bucket name for all uploads which made it impossible to find the file later.
This changes it to match the S3 Key. It is safe currently to hardcode to the first location as we only support single file upload.
Tested uploads work on the form runner and are represented as expected when rendered in the application-store e.g.
```
{
"name": "upload-business-plan",
"questions": [
{
"fields": [
{
"answer": "14bbb90f-1aa1-420a-a54e-5b002e33b976/1764158.jpeg",
"key": "rFXeZo",
"title": "Upload business plan",
"type": "file"
}
],
"question": "Management case",
"status": "COMPLETED"
}
],
"status": "COMPLETED"
}
```
> FS-1246: use S3 key as location/answer

- runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
Application store needs to receive a confirmation from the form runner that save and continue request came from the summary page in order to mark a form as completed. As such, we need to add a field in the metadata of the form runner that sends the confirmation when this happens.
> adding summary page identifier

- runner/src/server/plugins/engine/components/MultilineTextField.ts
- MultiTextField validation will now work on max words
> Fs 1620 multitext field no longer contains if max words have been exceeded

- runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- runner/src/server/plugins/engine/views/partials/form.html
- Changed the add another view to use a table rather than a summary list. Also change the data structure slightly for the passed in actions (seemed and but pointless to have them in an array).
> Fs 2195 correct table structure for add another

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/pageControllers/RepeatingFieldPageController.ts
- runner/src/server/plugins/engine/pageControllers/index.ts
- runner/test/cases/server/plugins/engine/pageControllers/RepeatingFieldPageController.test.ts
- Add another was causing loss of data when a users added a description field with a colon in it. This is a quick fix to avoid this. Add another needs a rework
return to and application with an colon within the …
> FS-2242 Fixing add another colon issues

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/components/MultilineTextField.ts
- runner/src/server/plugins/engine/components/TextField.ts
-  Allow html in hint when hideTitle is true
-  Also set hint to undefined instead of an empty string, this prevents the empty html element from appearing on the page
- (breaking change as any instances with `hideTitle` & html in `hint` will now render the html, [no occurrences of this exist as the `hideTitle` functionality was newly implemented in #102])
This code change has been manually tested via the form runner on a local dev environment.
The corresponding form changes have been migrated via a script seen here with test coverage: ..todo
> FS-2193: Allow html in hint when hideTitle is true

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/helpers.ts
- Form session identifier wasnt being used as part of the return url cause on change to break
> Fix for passing form_session_identifier

- .github/workflows/dluhc-build-and-deploy-with-forms.yml
Remove the auto trigger so that publishing a new docker image (with forms) is a manual step.
> bau-remove-auto-action-trigger

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/components/FreeTextField.ts
- runner/src/server/plugins/engine/components/MultilineTextField.ts
- runner/src/server/plugins/engine/components/types.ts
- runner/src/server/plugins/engine/views/components/freetextfield.html
- runner/src/server/views/layout.html
- Change tinymce selectors to be each unique component, this allows us to use multiple on the same form without affecting one another
- Move the import of tinymce to layout.html, this means we'll only import it once, rather than for each time the component is rendered, this was breaking functionality
- Add limit context to error messages, so the strings display properly with the number inside of them, also fixed for MultilineTextField
> FS-2538: Multiple fixes to FreeTextField

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/client/sass/application.scss
- runner/src/server/plugins/engine/views/components/freetextfield.html
A styling change for fixing bullet points on the summary page that were not showing
> Fixing styling issues for bullet points

- runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html
Adds origin to fetch calls, doesn't happen implicitly on external environments.
> BAU: Add window.location.origin to fetches

- .github/workflows/dluhc-build-and-publish.yml
- model/src/data-model/types.ts
- model/src/schema/schema.ts
- runner/src/server/forms/report-a-terrorist.json
- runner/src/server/forms/test.json
- runner/src/server/views/layout.html
- smoke-tests/designer/features/completeAForm.feature
- smoke-tests/designer/features/pageobjects/pages/formRunner.page.js
- smoke-tests/designer/features/steps/completeAForm.steps.js
- Can now customise footer with the new footer array with the form.
```
"footer": [
{
"href": "https://www.gov.uk/government/publications/community-ownership-fund-privacy-notice/community-ownership-fund-privacy-notice",
"text": "Privacy test"
},
{
"href": "https://www.google.com",
"text": "Cookies test"
},
{
"href": "https://www.gov.uk/government/publications/community-ownership-fund-privacy-notice/community-ownership-fund-privacy-notice",
"text": "Accessibility Statement test"
},
{
"href": "https://www.gov.uk/government/publications/community-ownership-fund-privacy-notice/community-ownership-fund-privacy-notice",
"text": "Contact Us test"
}
]
```
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> Footers are now customizable

- .github/workflows/dluhc-build-and-publish.yml
- fsd_config/form_jsons/cof_r2/cy/cefnogaeth-leol.json
- fsd_config/form_jsons/cof_r2/cy/gwybodaeth-am-yr-ased.json
- fsd_config/form_jsons/cof_r2/cy/lanlwythwch-y-cynllun-busnes.json
- fsd_config/form_jsons/cof_r2/cy/risg.json
- fsd_config/form_jsons/cof_r2/en/asset-information.json
- fsd_config/form_jsons/cof_r2/en/local-support.json
- fsd_config/form_jsons/cof_r2/en/risk.json
- fsd_config/form_jsons/cof_r2/en/upload-business-plan.json
- runner/src/server/index.ts
- runner/src/server/plugins/clientSideUpload.ts
- runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts
- runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
- runner/src/server/plugins/engine/plugin.ts
- runner/src/server/plugins/engine/views/components/clientsidefileuploadfield.html
- runner/src/server/services/uploadService.ts
- runner/src/server/views/partials/summary-row.html
- Change forms to use ClientSideFileUploadField
- Add crumb on front-end for authentication on POST route
- Fix download of files by adding form session identifier
Easy way? Use the dev environment with it deployed.
- [Deployed](https://github.com/communitiesuk/digital-form-builder/actions/runs/4762766179) via https://github.com/communitiesuk/digital-form-builder/compare/fs-2421-csu-auth-forms...communitiesuk:digital-form-builder:temp-test-forms-file-upload
Locally? you can test this with the following steps:
- Grab the docker image from the workflow
- Adjust the base image tag of the form runner in the [docker compose](https://github.com/communitiesuk/funding-service-design-docker-runner/blob/28f896ce70a1bcbf9c0cd8a7a1b14c1e01ecf42a/docker-comp …
> FS-2421: Client side upload auth & forms

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/components/MultiInputField.ts
- runner/src/server/plugins/engine/pageControllers/RepeatingSummaryPageController.ts
- Fix for how Date parts was displaying on the summary page and adding a todo
```
{
"type": "DatePartsField",
"name": "datePartsField",
"title": "Date parts field",
"options": {},
"schema": {}
}
```
> Fix for dateparts displaying as a Standard ISO

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/views/partials/summary-row.html
Nunjucks uses javascript, not python, and an empty list truthy in js is true. 
This change checks the length, so we render the text finally.
> FS-2759: Fix truthy logic

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/components/MultiInputField.ts
- runner/src/server/views/repeating-summary.html
- Add another components with an optional field in them now show not supplied instead of null on the summary page
> Optional add another now shows Not supplied

- fsd_config/form_jsons/night_shelter/local-need-and-support-ns.json
- runner/src/server/plugins/engine/components/ClientSideFileUploadField.ts
- Added the optionalText option for client side upload fields and changed the form to match the prototype
> Added optional check and corrected form

- runner/src/server/plugins/engine/components/YesNoField.ts
- Adding a missing mutilinput check to the yes not field to fix double label issues
> Adding multiinput check for yes no field label

- .github/workflows/dluhc-build-and-publish.yml
- fsd_config/form_jsons/cof_r3/cy/costau-gweithredol-cof-r3-w1.json
- fsd_config/form_jsons/cof_r3/cy/cyllid-sydd-ei-angen-cof-r3-w1.json
- fsd_config/form_jsons/cof_r3/en/funding-required-cof-r3-w1.json
- fsd_config/form_jsons/cof_r3/en/operational-costs-cof-r3-w1.json
- fsd_config/form_jsons/night_shelter/building-works-ns.json
- fsd_config/form_jsons/night_shelter/joint-applications-ns.json
- fsd_config/form_jsons/night_shelter/match-funding-ns.json
- fsd_config/form_jsons/night_shelter/objectives-and-activities-ns.json
- fsd_config/form_jsons/night_shelter/organisation-type-ns.json
- fsd_config/form_jsons/night_shelter/project-milestones-ns.json
- fsd_config/form_jsons/night_shelter/risk-and-deliverability-ns.json
Following on from https://github.com/communitiesuk/digital-form-builder/pull/230 - we make `MultiInputField`s explicitly required instead of implicitly, this should change the schema to re-validate upon re-routing prompting the user to fill in the section.  
Testing instructions:
- Pull the docker image from the github build (or build the forms locally, since only a form change)
- Launch the apps, and go to night shelter r2: http://localhost:3008/funding-round/nstf/r2
- Login, create an application
- Go to 1.2 Organisation type
- Select `Charity` & full out forms to summary page
- Select `Change` on "How is your organisation classified?"
- Change to "None of these"
- It should prompt you for 
- "How is your organisation classified?"
- Your trustees or committee members
Note, the file …
> FS-2957/FS-2927: Make MultiInputField explicit when required

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
Previously, we were just using `.find` on the summary page, this was only bringing back the first client side file upload component.  In this PR, we change from `.find` to `.filter`, so we get all instead of just the first, we also iterate over them.
- Pull the image from this PR 
- Add the image to your docker locally
- Add a form that has multiple client side file upload components
- Add AWS service-key credentials to your nodemon/form-runner
- `docker compose up form-runner --build`
- Navigate to the form you added
- Complete the form, uploading file at various points
- Observe the summary page now rendering multiple file names
> FS-2897: Use filter instead of find

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
The return to summary page acts as a queue, so we need to sort all the errors by their correct order.  Previously all file uploads would show at the end as the validation is separated and was just concatenated, now they show in the right order.
> FS-2972: Sort errors by order

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/plugins/engine/models/submission/WebhookModel.ts
`MonthYear` component is saved as a string, i.e `2003-02` - however this bit of a code made the assumption it was always an object, due to this, the date would get malformed, i.e:
```javascript
const [month, year] = Object.values("2003-02");
const dateString = `${year}-${month}-1`
console.log(dateString) // 0-2-1
console.log(new Date(dateString)) // Tue Feb 01 2000 00:00:00 GMT+0000 (Greenwich Mean Time)
```
This was causing all kinds of weird looking behaviour, as the dates were randomly shuffling themselves around due to the assumption that it was always an object, for a fix, I've put in to check that if it's a string, and if is, then the date is already formatted, so we can just return, we don't need to go through the transformation logic to turn it into a string.
> FS-2918: Return string if already string

- runner/src/server/views/confirmation.html
- runner/src/server/views/layout.html
- runner/src/server/views/summary.html
- runner/test/cases/server/feedback.test.js
FS-3348 removing feedback link from text in beta banner
Navigate to the frontend and view the beta banner
> Fs 3348 remove feedback link

- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
- When a question was changed, all the client side uploads questions would be put to the end. The questions should now appear in the correct order.
> Fix for wrong ordering on question change

- .github/workflows/dluhc-build-and-publish.yml
- fsd_config/form_jsons/cyp_r1/about-your-organisation-cyp.json
- runner/src/server/plugins/engine/components/UkAddressField.ts
https://dluhcdigital.atlassian.net/browse/FS-3515
- Fix to a issue with UkAddress field being optional and fixed routing for the about your organisation form
> Fix for Uk address field being optional

- runner/src/server/plugins/errorPages.ts
- Add stack traces to error logs, so we can identify where exceptions occurred
> FS-3522: Add stack trace to errors logs

- .gitattributes
- .gitignore
- README_DLUHC.md
- package.json
https://dluhcdigital.atlassian.net/browse/FS-3542
Changing node-based pre-commit to python-based pre-commit hook
If a node-based pre-commit hook already exists then remove it
```
rm .git/hooks/pre-commit
```
reinstall dependencies
```
yarn && yarn build
```
```
python -m venv .venv
source .venv/Scripts/activate
pip install pre-commit
pre-commit install
```
Now make a commit and observe python based pre-commit should kick in
> FS-3542 python based pre-commit hook

- .github/workflows/dluhc-build-and-publish.yml
- runner/src/server/views/layout.html
- Removed hyperlink on fund titles in form runner
> Replaced govuk header to remove fund title link

- .github/workflows/copilot_deploy.yml
- .github/workflows/dluhc-build-and-publish.yml
Stopped checking for tags existing if building from a branch, as we only tag on mian
Also updated workflow so deploy happens after build
> stop tag exists check if not on main (as we only tag on main)

- .github/workflows/anchore-scan.yml
Update key cache number as per documentation link in workflow to avoid running out of disk space during scan.
> BAU - increment scan number to reduce redundant cached layers

- fsd_config/form_jsons/cof/eoi/cof-eoi-funding.json
- Change the configuration for "How much capital funding are you requesting from COF?" 
- Now has a maximum of 2 million (2000000) & a prefix of a pound sign, since it's GBP
- Also updated the hint to match the specified image/mural
> FS-4081: Make max 2 million, add pound sign

- fsd_config/form_jsons/hsra/declaration-hsra.json
When declaration form section is completed and saved then after coming back from a partial form completion checkbox selection is not available
Login to HRSA : funding-round/hsra/r1
Start a new application
Click on “Declaration” form
Click the checkbox in the form
Submit the form
From the tasklist page return to the “Declaration” form and observe the page
Expected behaviour
Checkbox should be ticked on Save and Return
> FS-4360:declaration fix after save

- fsd_config/form_jsons/hsra/name-your-application-hsra.json
Duplicate heading “What would you like to name you application and “r” is missing in “your”
> FS-4351: application duplicate title fix and typo

- fsd_config/form_jsons/hsra_r1/hsra-r1-eligibility.json
- runner/src/server/plugins/engine/pageControllers/PageControllerBase.ts
- runner/test/cases/server/plugins/engine/NotifyViewModel.json
- runner/test/cases/server/plugins/engine/SaveViewModel.json
- runner/test/cases/server/plugins/engine/SummaryViewModel.json
- runner/test/cases/server/plugins/engine/WebhookModel.test.ts
- runner/test/cases/server/plugins/engine/WelshSummaryViewModel.json
- runner/test/cases/server/services/webhookService.test.ts
FS-4336: Fix form name for the HSRA question pages 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My changes do not introduce any new linting errors
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
> FS-4336: Fix form name for the HSRA question pages 

- copilot/fsd-form-runner/manifest.yml
remove additional alias as this is no longer being used
> BAU: remove additional alias

- runner/src/server/plugins/engine/models/viewModel.ts
- runner/src/server/plugins/engine/pageControllers/SummaryPageController.ts
- runner/src/server/views/partials/summary-detail.html
- runner/src/server/views/partials/summary-row.html
- runner/src/server/views/summary.html
This introduces a new flag `is_read_only_summary` that can be passed in the existing `metadata` payload when instantiating a new form. This instructs the summary page to not show "Change" links on the questions summary list and provides a direct back link.
The `is_read_only_summary` flag can be used along with `options.redirectPath` to direct the user to a read-only view of data they've previously provided.
Currently this fixes the back link and page title text for the summary page according to if the flag is set but it would be preferable for these values to be set using options bassed in my the service requesting a new form rather than fixed in the form logic -- if there are existing `options` payloads for customising this we should move to use those.
I'm applying the change to the …
> FS-3664 Read-only summary flag on the summary page

- copilot/fsd-form-runner/manifest.yml
switching off the old designer runner
Going according to the plan discussed and following is the URL 
https://dluhcdigital.atlassian.net/browse/FS-4597?focusedCommentId=601882
> [OLD-RUNNER] switching off the old designer runner
